### PR TITLE
BUGFIX: Error on closing if no file selected Fixes #50

### LINKED ISSUE #50: Error on closing if no file selected
First of all, this module just made my day! This thing is briljant and I love it! It makes life a lot easier, feels really stable, quick and elegant! 

I didn't do much testing, but it feels save to use in the project I'm working on already. I only got this errormessage though:
When picking/browsing a file from the CMS from within an UploadField an error occurs when the user did not select a file in the file-popup-window:

```
ERROR [Recoverable Error]: Argument 1 passed to DataList::byIDs() must be of the type array, null given, called in C:\WWW_Wamp\test\www\framework\forms\UploadField.php on line 1222 and defined
IN POST /test/www/admin/pages/edit/EditForm/field/MenuThumbnail/attach
Line 861 in C:\WWW_Wamp\test\www\framework\model\DataList.php
```
I didn't do further testing on this yet, but according to the message it seems like the module isn't checking if a valid selection was made before closing the window.
Some check for a valid fileselection and message to the user if that's not the case before closing/returning a value would be nice.

### PR DESCRIPTION
**Pull request by PeterhrCZ**
Simple fix solving the situation when no file is selected. User is now informed that he should select the file.
Translations were made using google.translator so they should be probably reviewed.

### CODE REVIEW

**Comment by unclecheese** [comment]
Thanks! Can you run a production build?

**Comment by PeterhrCZ** [comment]
You are welcome. 
I did a production build but it didn't generate the bundle.js file. I regenerated it with watch command. Was that what you were missing?
Also please remove my changes to the composer.json file. I should have made separate branch earlier.

**Comment by unclecheese** [comment]
"Watch" doesn't generate a production build -- use `npm run build:prod`. See contributing guidelines here: https://github.com/unclecheese/silverstripe-kickassets#contributing

**Comment by PeterhrCZ** [comment]
The production build is part of my first commit. That is how the file: bundle.min.js was generated. I am not sure what else do you expect. No other files were generated.

**Comment by unclecheese** [comment]
Gotcha. Sorry, I missed that. Thanks very much for this fix.

**Pull request merged**
